### PR TITLE
cycle sort using python

### PR DESCRIPTION
**Pull request by killer0921**

### CODE REVIEW

**Comment by OtacilioN** [comment]
Is this just spam? I am going to close this PR because it looks likes spam, if it is not, you are welcome to reopen and tell me.

**Comment by killer0921** [comment]
no,it was not a spam.
It is my first time contributing to hacktoberfest.So it might not be in a
proper way.
sorry for inconvenience.But please help me.

**Comment by killer0921** [comment]
i again made the PR's with same name. as i don't know how to reopen a
closed PR.
1. Gnome sort using python.
2. Stooge sort using python
3.  Radix sort using python
4.  Cycle sort using pyhton

**Comment by OtacilioN** [comment]
Hey @killer0921 this is not the way for contributing in this repository. Please read our [Contributing guide](https://github.com/OtacilioN/awesome-hacktoberfest-2019/blob/master/CONTRIBUTING.md)

You can make this pull requests to that repository: https://github.com/ReciHub/FunnyAlgorithms

**Pull request closed without merging**
